version: '3.8'

services:
  eureka-server:
    build:
      context: ./eureka-server
    image: eureka-server
    container_name: eureka-server
    ports:
      - "8761:8761"
    networks:
      - microservice-network

  api-gateway:
    build:
      context: ./api-gateway
    image: api-gateway
    container_name: api-gateway
    environment:
      SPRING_APPLICATION_NAME: api-gateway
      EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE: http://eureka-server:8761/eureka/
    depends_on:
      - eureka-server
    ports:
      - "8080:8080"
    networks:
      - microservice-network

  user-service:
    build:
      context: ./user-service
    image: user-service
    container_name: user-service
    ports:
      - "8081:8081"
    depends_on:
      - eureka-server
    networks:
      - microservice-network
    environment:
      SPRING_APPLICATION_NAME: user-service
      EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE: http://eureka-server:8761/eureka/

  account-service:
    build:
      context: ./account-service
    image: account-service
    container_name: account-service
    ports:
      - "8082:8082"
    depends_on:
      - eureka-server
    networks:
      - microservice-network
    environment:
      SPRING_APPLICATION_NAME: account-service
      EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE: http://eureka-server:8761/eureka/

  fund-transfer-service:
    build:
      context: ./fund-transfer-service
    image: fund-transfer-service
    container_name: fund-transfer-service
    ports:
      - "8083:8083"
    depends_on:
      - eureka-server
    networks:
      - microservice-network
    environment:
      SPRING_APPLICATION_NAME: fund-transfer-service
      EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE: http://eureka-server:8761/eureka/

  transaction-service:
    build:
      context: ./transaction-service
    image: transaction-service
    container_name: transaction-service
    ports:
      - "8084:8084"
    depends_on:
      - eureka-server
    networks:
      - microservice-network
    environment:
      SPRING_APPLICATION_NAME: transaction-service
      EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE: http://eureka-server:8761/eureka/

  sequence-generator:
    build:
      context: ./sequence-generator
    image: sequence-generator
    container_name: sequence-generator
    ports:
      - "8085:8085"
    depends_on:
      - eureka-server
    networks:
      - microservice-network
    environment:
      SPRING_APPLICATION_NAME: sequence-generator
      EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE: http://eureka-server:8761/eureka/

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./monitoring/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    networks:
      - microservice-network

  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - "3000:3000"
    restart: unless-stopped
    volumes:
      - ./monitoring/grafana/provisioning/datasources:/etc/grafana/provisioning/datasources
    networks:
      - microservice-network

networks:
  microservice-network:
    driver: bridge

volumes:
  mysql-data:
