# Cấu hình toàn cục
global:
  scrape_interval: 15s  # Tần suất thu thập dữ liệu
  evaluation_interval: 15s  # Tần suất đánh giá các quy tắc

# Cấu hình thu thập dữ liệu
scrape_configs:

  - job_name: 'transaction-service'
    metrics_path: '/actuator/prometheus'  # Đường dẫn tới metrics của Transaction Service
    static_configs:
      - targets: ['transaction-service:8084']

  - job_name: 'fund-transfer-service'
    metrics_path: '/actuator/prometheus'  # Đường dẫn tới metrics của Fund Transfer Service
    static_configs:
      - targets: ['fund-transfer-service:8083']

  - job_name: 'account-service'
    metrics_path: '/actuator/prometheus'  # Đường dẫn tới metrics của Account Service
    static_configs:
      - targets: ['account-service:8082']

  - job_name: 'sequence-generator'
    metrics_path: '/actuator/prometheus'  # Đường dẫn tới metrics của Sequence Service
    static_configs:
      - targets: ['sequence-generator:8085']

  - job_name: 'user-service'
    metrics_path: '/actuator/prometheus'  # Đường dẫn tới metrics của User Service
    static_configs:
      - targets: ['user-service:8081']

  - job_name: 'api-gateway'
    metrics_path: '/actuator/prometheus'  # Đường dẫn tới metrics của API Gateway
    static_configs:
      - targets: ['api-gateway:8080']
