# Cấu hình toàn cục
global:
  scrape_interval: 15s  # Tần suất thu thập dữ liệu
  evaluation_interval: 15s  # Tần suất đánh giá các quy tắc

# Cấu hình thu thập dữ liệu
scrape_configs:
  - job_name: 'eureka-server'
    metrics_path: '/actuator/prometheus'  # Đường dẫn tới metrics của Eureka Server
    static_configs:
      - targets: ['kubernetes.docker.internal:8761']

  - job_name: 'fund-transfer-service'
    metrics_path: '/actuator/prometheus'  # Đường dẫn tới metrics của Transfer Service
    static_configs:
      - targets: ['kubernetes.docker.internal:8083']

  - job_name: 'accountDto-service'
    metrics_path: '/actuator/prometheus'  # Đường dẫn tới metrics của Account Service
    static_configs:
      - targets: ['kubernetes.docker.internal:8082']

  - job_name: 'sequence-generator'
    metrics_path: '/actuator/prometheus'  # Đường dẫn tới metrics của Sequence Service
    static_configs:
      - targets: [ 'kubernetes.docker.internal:8085' ]

  - job_name: 'user-service'
    metrics_path: '/actuator/prometheus'  # Đường dẫn tới metrics của Sequence Service
    static_configs:
      - targets: [ 'kubernetes.docker.internal:8081' ]
#
#  - job_name: 'api-gateway'
#    metrics_path: '/actuator/prometheus'  # Đường dẫn tới metrics của API Gateway
#    static_configs:
#      - targets: ['api-gateway:8888']
