spring:
  application:
    name: sequence-generator

  datasource:
    url: jdbc:mysql://54.224.1.57:3306/banking_team2
    username: team2user
    password: team2password

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

server:
  port: 8083
